#! /bin/sh

bspc config border_width    4
bspc config window_gap      10

bspc config top_padding     4
bspc config bottom_padding  4
bspc config left_padding    4
bspc config right_padding   4

bspc monitor -d 1

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true
bspc config remove_disabled_monitors    true
bspc config remove_unplagged_monitors   true
bspc config merge_overlapping_monitors  true
bspc config focus_follows_pointer       false

# colors
# red
#bspc config focused_border_color        "#b22222"
# blue
#bspc config focused_border_color        "#215578"
# yellow
#bspc config focused_border_color        "#e55555"
# green
#bspc config focused_border_color        "#588032"
# violet
bspc config focused_border_color        "#70477f"
bspc config normal_border_color         "#252525"
bspc config urgent_border_color         "#b22222"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1


# rules
bspc rule -a jumanji            fullscreen=on
bspc rule -a QtCreator          fullscreen=on
bspc rule -a mplayer2           floating=on
bspc rule -a jetbrains-studio   fullscreen=on
bspc rule -a bspwm-exit         floating=on
